### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by KINGSABRI** [yoshidax/gitbook-plugin-book-summary-scroll-position-saver#1]
Thanks for the plugin but it didn't work for me. 
The installation is succeed but on reflected changes on the life book

I'm using Gitbook Desktop editor latest version 

This is not spam :) but the same case for your another plugin :(

**Comment by yoshidax** [comment]
sorry..

This plug-in works well if you are using a [gitbook-plugin-expandable-chapters](https://github.com/DomainDrivenArchitecture/gitbook-plugin-expandable-chapters).
Therefore, it is not necessary if you are not using a gitbook-plugin-expandable-chapters.

I did not notice.
Because I always because was using gitbook-plugin-expandable-chapters.

I think sorry for the confusion.

So, write a note to README.

thanks.

**Comment by KINGSABRI** [comment]
Hi, 
I'm using expandable-chapters plugin check [here](http://rubyfu.net/content/contributers/todo.html). Still facing the same issue :(

**Comment by yoshidax** [comment]
@KINGSABRI 

Thank you for the feedback! !
The structure of the summary area of your gitbook was unlike those who were my expectations.

Your structure:
`book-summary> navigation> summary`

Recent Gitbook:
`book-summary> summary`

My jQuery selector:
`$ ('.book-summary> summary')`

This problem is either due to the difference of the version I do not know.

However, I I think best to fix as this.
`$ ('.book-summary summary')`

Can it work well? :)

**Comment by KINGSABRI** [comment]
Hi @yoshidax 

I've changed "book-summary-scroll-position-saver.js" file to wha you've advised, and yah it's working like a charm! 

Thanks man!, keep it up
